name: radixdlt-publish-radixdlt-docker

on:
  release:
    types: [ published ]
  push:
    branches:
      - main
      - release\/*

jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-22.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@3d86a7cc43670094ac248017207be0295edbc31d
        with:
          access_token: ${{ github.token }}
  build-docker:
    name: Build deb package needed for Docker image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0b496e91ec7ae4428c3ed2eeb4c3a40df431f2cc
      - id: set_environment
        name: Set variables
        uses: ./.github/actions/set-variables
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          ref: ${{ steps.set_environment.outputs.git_ref }}
          fetch-depth: 0
      - name: Cache Gradle packages
        uses: actions/cache@b8204782bbb5f872091ecc5eb9cb7d004e35b1fa
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 17
        uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build deb file
        run: |
          cd radixdlt-core/radixdlt
          ../../gradlew deb4docker
          cd ../..
          find . -name "*.deb"
      - name: Archive deb package
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2
        with:
          name: build-deb
          path: |
            radixdlt-core/docker
            retention-days: 1
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
  publish-docker:
    needs: build-docker
    name: Build and push radixdlt Docker image
    environment: publish-artifacts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0b496e91ec7ae4428c3ed2eeb4c3a40df431f2cc
      - id: set_environment
        name: Set variables
        uses: ./.github/actions/set-variables
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        with:
          ref: ${{ steps.set_environment.outputs.git_ref }}
          fetch-depth: 0
      - name: Download distribution artifact
        uses: actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869
        with:
          name: build-deb
      - name: Set up JDK 17
        uses: actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Cache Gradle packages
        uses: actions/cache@b8204782bbb5f872091ecc5eb9cb7d004e35b1fa
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - id: get_version
        name: Get radixdlt version
        uses: ./.github/actions/get-version
        with:
          is_release: ${{ steps.set_environment.outputs.is_release }}
      - name: Login to Dockerhub (release)
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        if: "${{ steps.set_environment.outputs.is_release == 'true' }}"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GCR
        if: "${{ steps.set_environment.outputs.is_release == 'false' }}"
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_EU_DEV_JSON_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325
      - name: Docker build and push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          file: ./radixdlt-core/docker/Dockerfile.core
          tags: |
            ${{ steps.set_environment.outputs.radixdlt_image }}:${{ steps.get_version.outputs.docker_tag }}
          push: true
          platforms: linux/amd64,linux/arm64
          context: ./radixdlt-core/docker
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
